### ISSUE TITLE
`.where` is unusable

### ISSUE THREAD

**Issue by snario** [basecrm/basecrm-ruby#28]
The code is:

```
client = BaseCRM::Client.new(access_token: "mykey")
deals = client.deals.where(stage_id: 1337)
```

The error is:

```
/Users/lihorne/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/basecrm-1.1.3/lib/basecrm/http_client.rb:51:in `request': undefined method `to_h' for {}:Hash (NoMethodError)
	from /Users/lihorne/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/basecrm-1.1.3/lib/basecrm/http_client.rb:34:in `get'
	from /Users/lihorne/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/basecrm-1.1.3/lib/basecrm/services/deals_service.rb:41:in `where'
	from jobs/base.rb:21:in `<main>'
```

**Comment by snario** [comment]
Looks like a ruby version issue .. http://stackoverflow.com/questions/31683993/undefined-method-to-h-on-ruby-array
